apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  selector:
    matchLabels:
      app: mysql 
  serviceName: headless-svc-mysql
  replicas: 3 
  template:
    metadata:
      labels:
        app: mysql 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql-container
        image: mysql:9.5.0
        ports:
        - containerPort: 3306
          name: web-container
        env:
           - name: MYSQL_ROOT_PASSWORD
             value: "rootpassword"
        volumeMounts:
        - name: www
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "gp3"
      resources:
        requests:
          storage: 1Gi