apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
  labels:
    app: api-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-deploy
  template:
    metadata:
      labels:
        app: api-deploy
    spec:
      containers:
      - name: api
        image: elazarmeijers/sql-app-a:v4
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "mysql" 
        - name: DB_PASSWORD
          value: "rootpassword"